name: Hello World Workflow
on:
  push:
    branches: [ "main" ]
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - name: Say Hello
     run: echo "Hello, github action!"
   - name: Check out repository code
     uses: actions/checkout@v4
   - name: list files in the repository
     run: ls -l
